services:
  - type: web
    name: chapkat-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn sme_backend.wsgi:application
    envVars:
      - key: SECRET_KEY
        fromEnvVar: SECRET_KEY
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOST
        value: "${RENDER_EXTERNAL_HOSTNAME}"
      - key: DATABASE_URL
        fromEnvVar: DATABASE_URL
    healthCheckPath: /health

  - type: database
    name: chapkat-db
    provider: postgres
    plan: free
